### ISSUE TITLE
soft-bricked 3x Dazzler with the "video" example

### ISSUE THREAD

**Issue by hvrsalovic** [jamesbowman/py-bteve#2]
I was attempting to run the "video.py" example in the "examples" directory.  Since none of the sample AVI files that are named in the code exist in the Gameduino2 SD card ZIP file, I tried it with one of the ones that do exist..."fish.avi".
I adjusted the size tuple to the right size of the video (480 x 270 I believe) and ran it.

The HDMI output was while except for garbled first few scanlines. 
I retried this a few times, resetting the Dazzler each time

Eventually,  "gd.init()" stopped working, giving me this:
AssertionError: No response - is device attached?

Just powering up the Dazzler gives the "boot splash screen", and the Wii controller works to get to the menu.

However, it appears that the Dazzler no longer wants to communicate over SPI (or is giving some weird response back to init() )

**Comment by jamesbowman** [comment]
I suggest powering off the Dazzler, disconnecting the HDMI, the power it on and reconnect.

Which platform is this on?

**Comment by hvrsalovic** [comment]
multiple platforms tried.

Ok, what *apparently* was the issue is that my power supply to the Dazzler was barely cutting it
(** though for days on end all the more trivial examples ran just fine while being powered that way)
I guess the 'video' example (or my crashing version of it) pulled more current?? 
 I switched power supplies and the Dazzler came back to life.
